name: "Print action's workspace"
description: Prints the workspace (and more) this action is running in
runs:
  using: composite
  steps:
    - name: List all from work root
      shell: bash
      run: |
        find /home/runner/work

    - name: Find any workflow files from work root
      shell: bash
      run: |
        find /home/runner/work -type f -wholename '*/.github/workflows/*'

    - name: `cat` the first found workflow file
      shell: bash
      run: |
        find /home/runner/work -type f -wholename '*/.github/workflows/*' | xargs -n 1 cat
