on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cat `github` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(github) }}
          EOF

      - uses: cawfeecake/gha-workflow-notes/.github/actions/print-workspace-from-action@main
        with:
          action-path: ${{ github.path }}
          action-env: ${{ github.env }}
          action-step-summary: ${{ github.step_summary }}
          action-state: ${{ github.state }}
          action-output: ${{ github.output }}
