on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Test
      #   uses: cawfeecake/gha-workflow-notes/.github/actions/print-all@main
      - name: Test
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(github) }}
          EOF
          find /home/runner/work -type f -wholename '*/.github/workflows/*'
