on:
  workflow_dispatch:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print `github` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(github) }}
          EOF

          jq '.' response.json

      - name: Print `job` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(job) }}
          EOF

          jq '.' response.json

      - name: Print `needs` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(needs) }}
          EOF

          jq '.' response.json

      - name: Print `runner` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(runner) }}
          EOF

          jq '.' response.json
          
      - name: Print `steps` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(steps) }}
          EOF

          jq '.' response.json

  test:
    uses: cawfeecake/gha-workflow-notes/.github/workflows/reusable-search-for-workflows.yaml@main
    with:
      dir: /home/runner/work
