on:
  workflow_dispatch:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print `github` context
        run: |
          cat <<-'EOF' >response.json
          ${{ toJSON(github) }}
          EOF

          jq '.' response.json

  test:
    uses: cawfeecake/gha-workflow-notes/.github/workflows/reusable-search-for-workflows.yaml@main
    with:
      dir: /home/runner/work
      workflow-filepath: ${{ github.workflow }}
