on:
  workflow_dispatch:

jobs:
  test:
    uses: cawfeecake/gha-workflow-notes/.github/workflows/reusable-search-for-workflows.yaml@main
    with:
      dir: /home/runner/work
      workflow-filepath: ${{ github.workflow }}
